# Generated by Django 3.2.8 on 2021-10-15 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicação',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterField(
            model_name='publicação',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicação',
            name='usuario',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
