# Generated by Django 3.2.8 on 2021-10-18 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicação',
            name='titulo',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
