# Generated by Django 3.2.8 on 2021-10-15 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211015_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicação',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
