# Generated by Django 3.2.8 on 2021-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='texto',
            field=models.TextField(),
        ),
    ]
