# Generated by Django 3.2.8 on 2021-10-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211026_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicação',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
