# Generated by Django 3.2.8 on 2021-10-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_publicação_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicação',
            name='slug',
        ),
    ]
