# Generated by Django 3.2.8 on 2021-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211027_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='texto',
            field=models.TextField(),
        ),
    ]
