# Generated by Django 3.2.8 on 2021-10-29 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_publicação_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicação',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
