# Generated by Django 3.2.8 on 2021-10-29 18:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publicação_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicação',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='publicação',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
