# Generated by Django 3.2.8 on 2021-10-29 19:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211029_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicação',
            name='imagem_background',
            field=stdimage.models.StdImageField(default=1, upload_to='publicacoes/'),
            preserve_default=False,
        ),
    ]
