# Generated by Django 3.2.8 on 2021-10-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_publicação_imagem_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicação',
            name='imagem_background',
        ),
    ]
